name: Hello Actions

on:
  push:
    branches:
      - main

jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Diz oi
        run: echo "Hello Actions — funcionando!"

      - name: Mostra informações do runner
        run: |
          echo "Rodando no sistema: $RUNNER_OS"
          echo "Data e hora: $(date)"